default: &default
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci

production:
  adapter:  mysql2
  encoding: utf8
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:  5000
  username: <%= ENV["MC_DB_USERNAME"] %>
  password: <%= ENV["MC_DB_PASSWORD"] %>
  database: <%= ENV["MC_DATABASE"] %>
  host:     <%= ENV["MC_DB_HOSTNAME"] %>

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: kagomeshi_development
  pool: 5
  username: root
  password: password
  host: db

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: kagomeshi_test
  pool: 5
  username: root
  password:
  host: localhost
